Added new config macro test cases, removed old testing script (use bjam instead).
git-svn-id: http://svn.boost.org/svn/boost/trunk@16222 b8fc166d-592f-0410-95f2-cb63ce0dd405

diff --git a/boost/libs/config/configure b/boost/libs/config/configure
--- a/boost/libs/config/configure
+++ b/boost/libs/config/configure
@@ -2020,7 +2020,12 @@ echo $ECHO_N "checking $title (pass expected) ... $ECHO_C" >&6
       echo "$as_me:$LINENO: checking $title " >&5
 echo $ECHO_N "checking $title ... $ECHO_C" >&6
    fi
-   cat >conftest.$ac_ext <<_ACEOF
+   if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
@@ -2033,30 +2038,15 @@ echo $ECHO_N "checking $title ... $ECHO_C" >&6
 namespace ${namespace} = empty_boost;
 #endif
 
+int main(){ return ${namespace}::test(); }
 
-
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
- return ${namespace}::test();
-
-  ;
-  return 0;
-}
 _ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
+rm -f conftest$ac_exeext
 if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2066,21 +2056,29 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
 echo "${ECHO_T}OK" >&6
 
 else
-  echo "$as_me: failed program was:" >&5
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
+( exit $ac_status )
 echo "$as_me:$LINENO: result: Failed" >&5
 echo "${ECHO_T}Failed" >&6
    required_defs="$macroname $required_defs"
 
 fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
 
    if test $enable_test = 'yes'; then
 
    ac_ext=$use_ac_ext
    echo "$as_me:$LINENO: checking $title (fail expected) " >&5
 echo $ECHO_N "checking $title (fail expected) ... $ECHO_C" >&6
-   cat >conftest.$ac_ext <<_ACEOF
+   if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
@@ -2093,30 +2091,15 @@ echo $ECHO_N "checking $title (fail expected) ... $ECHO_C" >&6
 #error "this file should not compile"
 #endif
 
+int main() { return ${namespace}::test(); }
 
-
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-return ${namespace}::test();
-
-  ;
-  return 0;
-}
 _ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
+rm -f conftest$ac_exeext
 if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2127,13 +2110,16 @@ echo "${ECHO_T}failed" >&6
    required_undefs="$macroname $required_undefs"
 
 else
-  echo "$as_me: failed program was:" >&5
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
+( exit $ac_status )
 echo "$as_me:$LINENO: result: OK" >&5
 echo "${ECHO_T}OK" >&6
 
 fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
 
    fi
 
@@ -2158,7 +2144,12 @@ for file in $boost_base/libs/config/test/boost_has*.cxx; do
    if test $enable_test = 'yes'; then
    echo "$as_me:$LINENO: checking $title (pass expected) " >&5
 echo $ECHO_N "checking $title (pass expected) ... $ECHO_C" >&6
-   cat >conftest.$ac_ext <<_ACEOF
+   if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
@@ -2171,30 +2162,15 @@ echo $ECHO_N "checking $title (pass expected) ... $ECHO_C" >&6
 namespace ${namespace} = empty_boost;
 #endif
 
+int main(){ return ${namespace}::test(); }
 
-
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-return ${namespace}::test();
-
-  ;
-  return 0;
-}
 _ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
+rm -f conftest$ac_exeext
 if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2204,18 +2180,26 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
 echo "${ECHO_T}OK" >&6
 
 else
-  echo "$as_me: failed program was:" >&5
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
+( exit $ac_status )
 echo "$as_me:$LINENO: result: Failed" >&5
 echo "${ECHO_T}Failed" >&6
    required_undefs="$macroname $required_undefs"
 
 fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
 
    echo "$as_me:$LINENO: checking $title (fail expected) " >&5
 echo $ECHO_N "checking $title (fail expected) ... $ECHO_C" >&6
-   cat >conftest.$ac_ext <<_ACEOF
+   if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
@@ -2228,30 +2212,15 @@ echo $ECHO_N "checking $title (fail expected) ... $ECHO_C" >&6
 #error "this file should not compile"
 #endif
 
+int main(){ return ${namespace}::test(); }
 
-
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-return ${namespace}::test();
-
-  ;
-  return 0;
-}
 _ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
+rm -f conftest$ac_exeext
 if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2264,22 +2233,30 @@ echo "${ECHO_T}failed" >&6
 
 
 else
-  echo "$as_me: failed program was:" >&5
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
+( exit $ac_status )
 
    echo "$as_me:$LINENO: result: OK" >&5
 echo "${ECHO_T}OK" >&6
 
 
 fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
 
    else
 
    ac_ext=$use_ac_ext
    echo "$as_me:$LINENO: checking $title" >&5
 echo $ECHO_N "checking $title... $ECHO_C" >&6
-   cat >conftest.$ac_ext <<_ACEOF
+   if test "$cross_compiling" = yes; then
+  { { echo "$as_me:$LINENO: error: cannot run test program while cross compiling" >&5
+echo "$as_me: error: cannot run test program while cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+else
+  cat >conftest.$ac_ext <<_ACEOF
 #line $LINENO "configure"
 #include "confdefs.h"
 
@@ -2288,30 +2265,15 @@ echo $ECHO_N "checking $title... $ECHO_C" >&6
 
 #include "boost_$basename.cxx"
 
+int main(){ return ${namespace}::test(); }
 
-
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-return ${namespace}::test();
-
-  ;
-  return 0;
-}
 _ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
+rm -f conftest$ac_exeext
 if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (eval $ac_link) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
@@ -2324,15 +2286,18 @@ echo "${ECHO_T}Yes" >&6
 
 
 else
-  echo "$as_me: failed program was:" >&5
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
 cat conftest.$ac_ext >&5
+( exit $ac_status )
 
       echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 
 
 fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
 
    fi
 
@@ -3035,6 +3000,7 @@ fi
 
 
 fi
+
 
 
 
